### PR TITLE
create_ecr_repo: If the repository is an ECR repo check if it exists and create if it doesn't

### PR DESCRIPTION
**Pull request by hibbert**
This PR will do the following:-

* Check if the repository being built is an ECR repo
* If it is get the repository name without the ecr url
* Check if the repository exists in ECR
* If it doesn't create the repository

To do this I've also added the following dependencies:-

* awscli, installed via pip, so python and py-pip also installed
* aws_default_region for the source configuration to set the default region which is required when using the aws cli with ECR

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hibbert Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=199)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=199) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hibbert Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=199)!

**Comment by hibbert** [comment]
It might be good to have a separate resource for each repository type, although you may run into problems if someone has a FROM set to one repository type but requires to push the resulting image to another.

The resource is lacking the ability to create ECR repos on the fly without this (or something similar) meaning it's not end to end automation for pushing images to the ECR. It also doesn't support assuming roles which is required if you are working across account - https://github.com/concourse/docker-image-resource/issues/202

**Comment by ghostsquad** [comment]
ECR repositories, like Github repos, should not be created from a concourse pipeline. They should be created outside and assigned appropriate permissions. I highly suggest that this PR be closed.

This would definitely cause issues for us, as we use terraform to create/manage ECR repos, and we _don't_ want things created automatically if they don't exist. We want this to fail, as it also indicates a potential typo.

**Comment by vito** [comment]
Gonna close this out - thanks for taking the time to submit it though!

FWIW I've started to break this resource up - the start of that work is here: https://github.com/concourse/registry-image-resource

I've yet to begin integrating this new resource type with ECR or GCR but I'd be interesting in seeing what that looks like going forward. With this new resource the scope is smaller and more manageable, so hopefully supporting different registries doesn't feel like so much cognitive overhead and risk (well, as long as we do it properly).

**Pull request closed without merging**
