### PR TITLE
add labels to metadata if any

### PR DESCRIPTION
**Pull request by endemics**
This is a proposed implementation for #125

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@endemics Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=128)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=128) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@endemics Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=128)!

**Comment by jtarchie** [comment]
@endemics, we are still not totally familiar with the labels and metadata. Are you able to provide a screenshot of the metadata being added to concourse? This would help us out a lot.

**Comment by endemics** [comment]
This PR is actually an incorrect implementation for #125 . It should not be done in `check` and not in `out`

**Pull request closed without merging**
