### PR TITLE
Add support for `--no-cache` option for `docker build`.

### PR DESCRIPTION
**Pull request by oppegard**

### CODE REVIEW

**Comment by vito** [comment]
What does passing --no-cache do? Seems like it'd not have any effect anyway since the container is fresh every time.

**Comment by oppegard** [comment]
Correct, passing --no-cache won't have any effect since the container is fresh. However, I figured we might as well pass the option down to docker in the event things change in the future (volume support?),

**Comment by vito** [comment]
Gotcha. That probably won't be changing; when we do the volume stuff we ideally won't be changing semantics like that (otherwise it's kind of a leaky optimization).

**Comment by oppegard** [comment]
Want to merge as-is, or should I re-submit without the --no-cache option?

**Comment by vito** [comment]
Removing the `--no-cache` would be great; it's a bit misleading as-is. Maybe just have a `cache` option which defaults to true?

**Comment by oppegard** [comment]
Renamed parameter to  `cache` and squashed to a single commit.

**Comment by vito** [comment]
thanks!

**Pull request merged**
