### PR TITLE
Add digest to source, Fixes #187, Fixes #194

### LINKED ISSUE #187: Source does not support specifying image digest
The docker image resource supports pulling images by tag. The [docker commandline](https://docs.docker.com/engine/reference/commandline/pull/) supports pulling images by tag and digest.

Would a pull request to add `digest` to the [source configuration](https://github.com/concourse/docker-image-resource#source-configuration) be accepted?

Original description:
----
This may be an issue with how concourse itself works, if so, maybe this is a documentation issue.

The ~~docker image resource supports pulling images by tag and digest~~. If an image is specified by tag initially, and then the configuration is updated to specify a previously pulled digest, the most recent version of the docker image is used. 

Example:
```
# original specification
- resources:
  - name: ansible
    type: docker-image
    source:
      repository: williamyeh/ansible
      tag: ubuntu16.04
```

Updated to:
```
- resources:
  - name: ansible
    type: docker-image
    source:
      repository: williamyeh/ansible
      digest: sha256:fad6172150bfd446bae9948b6fcec2fff95368448690fc3d807904f9ce24a272 # previous version of the `ubuntu16.04` tag, ubuntu16.04 now resolves to a different digest
```

Tasks resolve to using image `c14d84964da7ff870c9daf184f9d130919abb6de44f62fb54e68f26bbc71a7e1`.

A workaround is to turn off more recent versions of resource:
screen shot 2018-03-28 at 10 15 32 pm

I believe that specifying the earlier pulled digest is treated as "already pulled" by the resource check, but then treated as an "older version" by concourse since there are newer resource versions. 

One possible fix may be to add a hash of the specification parameters into the version metadata of this resource so that changing the specification parameters forces a new concourse resource version, here:

https://github.com/concourse/docker-image-resource/blob/380a4ca0fad939715a30a18c60160598fd5b1faf/assets/in#L97-L104

I'm happy to contribute a PR if that makes sense.

Edit: I suppose changing the resource name would also work.

### LINKED ISSUE #194: allow to specify image digest and do not reach out to registry if digest is available in cache
We were facing some hangs on our pipeline recently caused by the docker image registry being down.

Proposal:

I want to be able to pin down the image used by a task to an immutable digest anyway, sth like.
```
- name: hello-world-docker-image
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: sample_docker_registry/concourse-tutorial-hello-world
    digest: "sha256:a8a5091416981a6dd5d4fc53fb4773133e8c7627202d55831d636c60d2d1a2e1"
```

then, the  `check` and `in` logic of docker-image-resource could first check if the digest is available in the local cache , e.g. using

```
docker images sample_docker_registry/concourse-tutorial-hello-world --format "{{.Digest}}"
```

and spare the roundtrip to the docker image registry altogether if the digest is found locally.
This would make concourse pipelines more resilient to outages of docker registries.

### PR DESCRIPTION
**Pull request by creack**
- Add support for source digest.
- Verify the resulting digest.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@creack Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=229)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=229) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@creack Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=229)!

**Comment by vito** [comment]
Thanks for taking the time to submit this!

We're actually going to be tackling https://github.com/concourse/concourse/issues/2439 very soon which will enable users to do this without any changes to this resource type (and enable users to do this for *all* resource types).

Would you be OK with just closing this for now in light of https://github.com/concourse/docker-image-resource/issues/190 (primarily the 'too many knobs' concern)? We should be picking up the issue I linked very soon - it's at the top of the "core" backlog and we need it done before we can continue on the "spaces" epic.

**Comment by achawki** [comment]
Since this PR addresses #194 just partly, `check` would still always reach out the docker registry => concourse jobs cannot be scheduled anymore in case of a registry downtime, we opened https://github.com/concourse/docker-image-resource/pull/231 . Just for discussion.

**Comment by creack** [comment]
Closing in favor of concourse/concourse#2439

This is a critical security issue, I hope it will be addressed soon.

**Comment by creack** [comment]
For reference, I've been using this in the meantime:

```
  - name: docker-image-digest-unchecked
    type: docker-image
    privileged: true
    source:
      params:     {skip_download: true}
      repository: creack/docker-image-resource
  - name: docker-image-digest
    type: docker-image-digest-unchecked
    privileged: true
    source:
      params:     {skip_download: true}
      repository: creack/docker-image-resource
      digest:     sha256:45b2409bdc9a6d49ac56a83bb32715f9389848d1c1a33a98569106c383dfa946
```

**Pull request closed without merging**
