### PR TITLE
Update amazon-ecr to working version

### PR DESCRIPTION
**Pull request by pecigonzalo**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pecigonzalo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=104)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=104) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pecigonzalo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=104)!

**Comment by bramswenson** [comment]
+1

**Comment by willejs** [comment]
@vito can you merge this please?
Currently the resource doesent support aws ecs task roles, as it uses go awssdk 1.1.28 instead of 1.25+. You can see the diff [here](https://github.com/awslabs/amazon-ecr-credential-helper/compare/77ede7e8c97aab375302fc8770a7a88a5a1af275...589f7070767646f2b220504930f803accb1e88a7#diff-2b394058ed387c715b8759fca3dfd933R11) that upgrades to 1.6.5 
Apart from that it looks like it adds a bunch of tests and a few minor fixes.

**Comment by vito** [comment]
shouldn't this also have a bunch of changes under `vendor/`? updating just `Godeps.json` won't bump the actual code

**Comment by pecigonzalo** [comment]
Bah, you are correct, i just forgot to commit that as Im used to not putting the `vendor` in the repo. Will push ASAP.

**Comment by vito** [comment]
cool, thanks!

**Comment by willejs** [comment]
@pecigonzalo can you add the vendored deps plz? I really want to use this...

**Comment by pecigonzalo** [comment]
@vito I got this to compile before, but now i can't get godep to pull the dependencies, honestly I hate godep, would you prefer to just re open this yourself?

**Comment by willejs** [comment]
Yeah, i was going to look at this, but the build scripts confused me. 
Clone repo into that folder and check out to that hash, then delete the .git folder if you want to cheat.

**Comment by willejs** [comment]
@pecigonzalo @vito I have had a go at this here
https://github.com/concourse/docker-image-resource/pull/107

**Comment by vito** [comment]
closed via #107 

there's no CI at the moment for this resource as there are no unit tests; we rely on integration in our main pipeline, and it'd be expensive to run that for PRs

**Pull request closed without merging**
