### PR TITLE
set Docker build arg with contents of arbitrary file

### PR DESCRIPTION
**Pull request by StephenWithPH**
This PR fixes the specific behavior raised in https://github.com/concourse/docker-image-resource/issues/203 (*semver resource not usable as build_arg*). More generally, it supports setting a Docker build arg with the contents of an arbitrary file.

It is useful when the contents of a file cannot be coerced into the form necessary for `build_args_file`.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@StephenWithPH Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=240)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=240) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@StephenWithPH Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=240)!

**Comment by haljin** [comment]
Is anything ever going to happen with this? We could really use this feature

**Comment by vito** [comment]
@haljin @StephenWithPH Sorry I missed this, but at this point I think it's better to just close this and push folks torwards the [`builder` task](https://github.com/concourse/builder-task) and [`registry-image` resource](https://github.com/concourse/registry-image-resource) instead of adding more functionality to this resource.

**Pull request closed without merging**
