### PR TITLE
Multi tag

### PR DESCRIPTION
**Pull request by gcmalloc**
took https://github.com/concourse/docker-image-resource/pull/124 and added the required tests.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gcmalloc Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=171)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=171) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gcmalloc Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=171)!

**Comment by 2color** [comment]
This is immensely useful!

**Comment by jchesterpivotal** [comment]
Riff team are pretty keen on this. We'd like to tag our images with build numbers, release version numbers and I imagine we'll think of others.

**Comment by jchesterpivotal** [comment]
We're still keen on this. Is there anything I can do to help get this PR into master?

**Comment by willejs** [comment]
@jtarchie @vito can you review this please? Looks like its complete 😸

**Comment by alpha-er** [comment]
Any docs for this? :)

**Comment by vito** [comment]
Thanks! Sorry for the delay.

**Pull request merged**
