### PR TITLE
Handle when /etc/passwd is missing because the image is built using s…

### PR DESCRIPTION
**Pull request by robdaemon**
…cratch or another base layer that does not provide that file.

### CODE REVIEW

**Comment by robdaemon** [comment]
This resolves #27

**Comment by vito** [comment]
Not a fan of assuming failure to run `docker run` is due to missing `/etc/password` - it could be any number of things. Instead https://github.com/concourse/docker-image-resource/tree/master/cmd/print-metadata should probably be made durable to this.

**Comment by robdaemon** [comment]
I was debating where to handle that. I can make print-metadata more resilient instead.

**Comment by vito** [comment]
Cool, thanks for looking into this!

**Comment by robdaemon** [comment]
Okay, updated the PR. Handling the lack of /etc/passwd and parsing of /etc/passwd as a recoverable error instead of a panic condition.

**Comment by robdaemon** [comment]
Is there anything else that needs to be done on this PR so it can be merged upstream? I'm currently running my fork in production, and I'd like to stick to upstream.

**Pull request merged**
