### PR TITLE
Some basic tests for tag_as_latest

### PR DESCRIPTION
**Pull request by jerith**
Two simple non-ECR tests in the `DockerImageResource` suite.

(I mostly wrote these so I'd have something to work from when writing tests for #124.)

### CODE REVIEW

**Comment by jerith** [comment]
@jtarchie I'd like to get this merged before I write tests for #124.

**Comment by jtarchie** [comment]
@jerith, thanks for following up on this!

**Comment by jtarchie** [comment]
@jerith, these tests don't pass for me. I tried to clean them up with this [diff](https://gist.github.com/jtarchie/008f7a10a561a00a53a07ada42922738). The timeout for the daemon always timesout though with `waiting for docker to come up...`.

**Comment by jtarchie** [comment]
We are considering this pull request dead due to inactivity. Please feel free to reopen a new pull request with the requested changes. Thanks!

**Pull request closed without merging**
